// Mock pricing data for three categories
export const pricingData = {
  gbp: {
    key: "gbp",
    label: "Google Business Profile",
    title: "Google Business Profile Optimization",
    subtitle: "Get found by local customers actively searching for your business.",
    accent: "#FCC419", // yellow
    accentSoft: "#FFF7DC",
    cardSoft: "#FFF8E7",
    dotColor: "#FCC419",
    dotColorDeluxe: "#22C55E",
    sideCardButton: "white",
    sideCardButtonText: "#0F0F10",
    plans: [
      {
        tier: "Basic",
        name: "Starter",
        desc: "Set up and optimize your presence",
        price: "₹1,199",
        meta: "One-time  ·  + taxes  ·  5–7 days",
        features: [
          { ok: true, t: "Complete profile setup" },
          { ok: true, t: "5–10 high-quality photos" },
          { ok: true, t: "Accurate business information" },
          { ok: true, t: "Category optimization" },
          { ok: true, t: "Business description writing" },
          { ok: true, t: "Website link setup" },
          { ok: false, t: "Google Posts" },
          { ok: false, t: "Competitor analysis" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#FCC419",
      },
      {
        tier: "Premium",
        name: "Pro",
        desc: "Dominate local search results",
        price: "₹1,499",
        meta: "One-time  ·  + taxes  ·  7–10 days",
        features: [
          { ok: true, t: "Everything in Starter" },
          { ok: true, t: "15–20 professional photos" },
          { ok: true, t: "2 Google Posts per month" },
          { ok: true, t: "Competitor analysis" },
          { ok: true, t: "Review response templates" },
          { ok: true, t: "Q&A optimization" },
          { ok: true, t: "15-day support" },
          { ok: false, t: "Active review management" },
        ],
        cta: "Schedule Consultation",
        popular: true,
      },
      {
        tier: "Deluxe",
        name: "Elite",
        desc: "Complete local dominance",
        price: "₹1,999",
        meta: "One-time  ·  + taxes  ·  10–15 days",
        features: [
          { ok: true, t: "Everything in Pro" },
          { ok: true, t: "20+ professional photos/videos" },
          { ok: true, t: "4 Google Posts per month" },
          { ok: true, t: "Active review management (1 month)" },
          { ok: true, t: "Video walk-through included" },
          { ok: true, t: "Monthly insights report" },
          { ok: true, t: "30-day support & monitoring" },
          { ok: true, t: "Competitor tracking" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#22C55E",
      },
    ],
  },
  web: {
    key: "web",
    label: "Website Development",
    title: "Professional Website Development",
    subtitle: "A stunning, fast-loading website that turns visitors into customers.",
    accent: "#1E62D8",
    accentSoft: "#DCE7FA",
    cardSoft: "#EEF2FB",
    dotColor: "#1E62D8",
    dotColorDeluxe: "#1E62D8",
    sideCardButton: "#1E62D8",
    sideCardButtonText: "#FFFFFF",
    plans: [
      {
        tier: "Basic",
        name: "Launch",
        desc: "Your web presence starts here",
        price: "₹9,499",
        meta: "One-time  ·  + taxes  ·  Delivery: 3–5 days",
        features: [
          { ok: true, t: "Up to 5 pages" },
          { ok: true, t: "Mobile-friendly responsive design" },
          { ok: true, t: "Contact form + Google Maps embed" },
          { ok: true, t: "Basic SEO setup" },
          { ok: true, t: "Social media links" },
          { ok: true, t: "Domain & hosting guidance" },
          { ok: true, t: "1 round of revisions" },
          { ok: false, t: "WhatsApp button" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#1E62D8",
      },
      {
        tier: "Premium",
        name: "Impress",
        desc: "A visually rich website that wows",
        price: "₹14,999",
        meta: "One-time  ·  + taxes  ·  Delivery: 7–10 days",
        features: [
          { ok: true, t: "Everything in Launch" },
          { ok: true, t: "Up to 8 pages" },
          { ok: true, t: "Professional media embedded" },
          { ok: true, t: "3D animations on homepage" },
          { ok: true, t: "Custom designed sections" },
          { ok: true, t: "WhatsApp button" },
          { ok: true, t: "Google Analytics setup" },
          { ok: true, t: "2 rounds of revisions" },
        ],
        cta: "Schedule Consultation",
        popular: true,
      },
      {
        tier: "Deluxe",
        name: "Convert",
        desc: "Built to generate leads & sales",
        price: "₹19,999",
        meta: "One-time  ·  + taxes  ·  Delivery: 12–15 days",
        features: [
          { ok: true, t: "Everything in Premium" },
          { ok: true, t: "Up to 12 pages" },
          { ok: true, t: "Custom shopping cart system" },
          { ok: true, t: "Payment gateway integration" },
          { ok: true, t: "WhatsApp auto-messaging" },
          { ok: true, t: "Advanced 3D animations" },
          { ok: true, t: "Full SEO optimization" },
          { ok: true, t: "3 rounds of revisions" },
          { ok: true, t: "1 month free post-delivery support" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#1E62D8",
      },
    ],
  },
  smm: {
    key: "smm",
    label: "Social Media Management",
    title: "Social Media Management",
    subtitle: "Consistent, engaging content that builds your audience and drives growth.",
    accent: "#5B1A9C",
    accentSoft: "#E9D8FB",
    cardSoft: "#F4ECFB",
    dotColor: "#5B1A9C",
    dotColorDeluxe: "#5B1A9C",
    sideCardButton: "#5B1A9C",
    sideCardButtonText: "#FFFFFF",
    plans: [
      {
        tier: "Basic",
        name: "Active",
        desc: "Stay consistent and visible",
        price: "₹4,999",
        priceSuffix: "/mo",
        meta: "Or ₹14,999 for 3 months  ·  Instagram + Facebook",
        features: [
          { ok: true, t: "8 posts/month" },
          { ok: true, t: "Basic graphic design per post" },
          { ok: true, t: "Hashtag research & optimization" },
          { ok: true, t: "Profile bio optimization" },
          { ok: true, t: "1 story/week" },
          { ok: true, t: "Basic comment management" },
          { ok: false, t: "Reels/video content" },
          { ok: false, t: "Monthly reports" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#5B1A9C",
      },
      {
        tier: "Premium",
        name: "Grow",
        desc: "Scale your audience effectively",
        price: "₹8,999",
        priceSuffix: "/mo",
        meta: "Or ₹24,999 for 3 months  ·  + LinkedIn or YouTube",
        features: [
          { ok: true, t: "Everything in Basic" },
          { ok: true, t: "12 posts/month (mix of content)" },
          { ok: true, t: "Professional branded graphics" },
          { ok: true, t: "SEO-optimized captions" },
          { ok: true, t: "3 stories/week + reels" },
          { ok: true, t: "DM & comment management" },
          { ok: true, t: "Monthly performance report" },
          { ok: false, t: "Paid ad campaigns" },
        ],
        cta: "Schedule Consultation",
        popular: true,
      },
      {
        tier: "Deluxe",
        name: "Dominate",
        desc: "Hands-off social media excellence",
        price: "₹14,999",
        priceSuffix: "/mo",
        meta: "Or ₹39,999 for 3 months  ·  All platforms",
        features: [
          { ok: true, t: "Everything in Premium" },
          { ok: true, t: "20 posts/month" },
          { ok: true, t: "Professional video editing" },
          { ok: true, t: "WhatsApp broadcast management" },
          { ok: true, t: "1 paid ad campaign/month" },
          { ok: true, t: "Influencer outreach" },
          { ok: true, t: "Content calendar planning" },
          { ok: true, t: "Weekly performance check-ins" },
        ],
        cta: "Get Started",
        popular: false,
        dot: "#5B1A9C",
      },
    ],
  },
};

export const tabOrder = ["gbp", "web", "smm"];
